# Generated by Django 3.0.8 on 2020-09-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('posterUrl', models.CharField(max_length=1000)),
                ('netflixOk', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('liked_movies', models.ManyToManyField(related_name='liked_movies', to='backend.Movie')),
                ('unliked_movies', models.ManyToManyField(related_name='unliked_movies', to='backend.Movie')),
            ],
        ),
    ]
