# Generated by Django 3.0.8 on 2020-09-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_movie_moviedbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
